FIXED_KEYS = ['Name','Experience','Education','Skills', 'Certificates']
VARIABLE_KEYS = ['Experience', 'Education']
ORDERED_KEYS = ['Name','Experience','Education','Skills', 'Certificates']
DOB_PROMPT = 'Check that the following date is in YYYY/MM/DD. Correct it if its not in the same format, otherwise return the same: '
SUMMARY_PROMPT_CONVERT = 'rewrite my CV according to the latest job application trends. Follow the format'
TEMPERATURE_SUMMARY_PROMPT_CONVERT = 0.8
SUMMARY_PROMPT_IMPROVER = 'Improve the following text quality:'
TEMPERATURE_SUMMARY_PROMPT_IMPROVER = 0.3
OPENAIMODEL = 'text-davinci-003'
OPENAIKEY = "api_key"
TEMPLATE_FILE = 'cv_template.txt'
EXPERIENCE_PROMPT_CONVERT = "Make the text more appealing for a recruiter:"
RESULT_FILE = 'cv_improved.txt'
